#
# Makefile --Build rules for "xtd", my extensions to the C library.
#
language = c
LIB_ROOT = ..

C_SRC = heap.c
H_SRC = heap-template.h heap.h

include makeshift.mk library.mk
install: install-lib-include
uninstall: uninstall-lib-include
