#
# Makefile --Build rules for "xtd/stack", a stack implementation.
#
language = c
LIB_ROOT = ..

C_SRC = stack.c
H_SRC = array.h stack.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
