#
# Makefile --Build rules for "apex/apex", core stuff.
#
language = c
LIB_ROOT = ..
subdir = apex

C_SRC = version.c
H_SRC = gnuattr.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
