#
# Makefile --Build rules for "apex/sys", system-related stuff
#
language = c
LIB_ROOT = ..
subdir = apex

C_SRC = pidfile.c sysenum.c systools.c
H_SRC = sysenum.h syslog-standalone.h systools.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
