#
# Makefile --Build rules for "xtd/xtd", core stuff.
#
language = c
LIB_ROOT = ..
subdir = xtd

C_SRC = version.c
H_SRC = gnuattr.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
