#
# Makefile --Build rules for "xtd/sys", system-related stuff
#
language = c
LIB_ROOT = ..

C_SRC = memory_file.c pidfile.c systools.c
H_SRC = memory_file.h systools.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
