#
# Makefile --Build rules for "xtd/sys", system-related stuff
#
language = c
LIB_ROOT = ..
subdir = xtd

C_SRC = pidfile.c sysenum.c systools.c
H_SRC = sysenum.h systools.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
