#
# Makefile --Build rules for "xtd/sys", system-related stuff
#
language = c
LIB_ROOT = ..

C_SRC = pidfile.c systools.c
H_SRC = systools.h

include devkit.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
