#
# Makefile --Build rules for the string components of xtd.
#
language = c
LIB_ROOT = ..

C_SRC = estring.c memswap.c stredit.c strlist.c strparse.c \
    textbuf.c
H_SRC = estring.h strparse.h textbuf.h

include devkit.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
