#
# Makefile --Build rules for "xtd/array", various slab/array ADTs.
#
language = c
LIB_ROOT = ..

C_SRC = binsearch.c compare.c heap-sift.c heap.c pool.c queue.c \
    stack.c
H_SRC = array.h binsearch.h compare.h heap.h pool.h queue.h stack.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
