#
# Makefile --Build rules for "xtd/stack", a stack implementation.
#
language = c
LIB_ROOT = ..

C_SRC = heap-sift.c heap.c queue.c stack.c
H_SRC = array.h heap.h queue.h stack.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
