#
# Makefile --Build rules for "xtd", my extensions to the C library.
#
language = c
LIB_ROOT = ..
subdir = xtd

C_SRC = clink.c linkalloc.c
H_SRC = clink.h slink.h

include makeshift.mk library.mk
install: install-lib-include
uninstall: uninstall-lib-include
