#
# Makefile --Build rules for "xtd", my extensions to the C library.
#
language = c
LIB_ROOT = ..

C_SRC = clink.c linkalloc.c
H_SRC = clink.h link.h

include devkit.mk library.mk
install: install-lib-include
uninstall: uninstall-lib-include
