#
# Makefile --Build rules for "xtd/misc", miscellaneous stuff
#
language = c
LIB_ROOT = ..

C_SRC = binsearch.c sysenum.c
H_SRC = binsearch.h sysenum.h

include devkit.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
