#
# Makefile --Build rules for "xtd/misc", miscellaneous stuff
#
language = c
LIB_ROOT = ..

C_SRC = binsearch.c compare.c sysenum.c
H_SRC = binsearch.h compare.h sysenum.h syslog-standalone.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
