#
# Makefile --Build rules for "xtd", my extensions to the C library.
#
language = c
LIB_ROOT = ..

C_SRC = http.c protocol.c url.c
H_SRC = http.h protocol.h url.h

include devkit.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
