#
# Makefile --Build rules for "apex/tfile", timestamp-oriented files.
#
language = c
LIB_ROOT = ..
subdir = apex

C_SRC = tfile.c
H_SRC = tfile.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
