#
# Makefile --Build rules for some demo stuff.
#
language = c nroff sh

BUILD_PATH = ../libxtd

MAN1_SRC = wakeup.1
C_MAIN_SRC = log-demo.c wakeup.c
C_SRC = log-demo.c wakeup.c

include makeshift.mk 

$(C_MAIN):      -lxtd
#install:	install-all
#uninstall:	uninstall-all
