#
# Makefile --Build rules for "xtd/tfile", timestamp-oriented files.
#
language = c
LIB_ROOT = ..
subdir = xtd

C_SRC = tfile.c
H_SRC = tfile.h

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
