#
# Makefile --Build rules for "xtd/tfile", timestamp-oriented files.
#
language = c
LIB_ROOT = ..

C_SRC = tfile.c
H_SRC = tfile.h

include devkit.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
