#
# Makefile --build rules for a simple statechart.
#
LIB_ROOT = ..
subdir = apex
language = c
H_SRC = stately.h
C_SRC = stately.c

include makeshift.mk library.mk

install: install-lib-include
uninstall: uninstall-lib-include
